### ISSUE TITLE
multi_face version calculation

### ISSUE THREAD

**Issue by BojingJiang** [pandyah5/aps360-project#13]
Could you please explain the calculation on line 51, 62, 63, and 75?

**Comment by harmangill07** [comment]
On line 51: The x coordinate of the bottom of the face is being calculated. Since the model makes the chin as the center of the bounding box, the x coordinate is equal to the corner coordinate plus half the width of the bounding box.

On line 62, 63: It finds the middle point of the bounding box, which is the corner coordinate (xmin, ymin) plus half the width and half the height of the bounding box.

On line 74: The width of the mask is being set to the distance from the left ear to the right ear, with a scaling factor of 1.15 because part of the mask is the strings on the side.

On line 75: The height of the mask is being set as the distance from the bottom of the face to the average height of the ears. That's why its (left_ear + right_ear) / 2 to get the average between the two.
